dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.0+4
  path: ^1.8.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
